name: 'Helm2S3 Publisher'
description: 'Github action that allows publishing helm chart to S3'
inputs:
  bucket:
    description: 'Target S3 bucket'
    required: true
  folder: 
    description: 'Path in S3 bucket'
    required: true
    default: "stable"
  chart:
    description: 'Helm chart name'
    required: true
  version:
    description: 'Helm chart version'
    required: true
  source: 
    description: 'Path to chart'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: false
  aws-secret-access-key: 
    description: 'AWS Secret Access Key'
    required: false
  aws-region: 
    description: 'AWS Region, e.g. us-east-1'
    required: false
runs:
  using: "composite"
  steps:
    - run: helm plugin install https://github.com/hypnoglow/helm-s3.git
      shell: bash 

    - run: helm repo add ${{ inputs.chart }} s3://${{ inputs.bucket }}/${{ inputs.folder }}/${{ inputs.chart }}
      shell: bash 
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
          
    - run: helm package ${{ inputs.source }} --version ${{ inputs.version }}
      shell: bash 

    - run: helm s3 push ./${{ inputs.chart }}-${{ inputs.version }}.tgz ${{ inputs.chart }} --force
      shell: bash 
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}